name: HighDimensionalClustering
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - gdown
    - igraph
    - partition-igraph
    - celluloid
    - seaborn
    - imbalanced-learn
    - git+https://github.com/TutteInstitute/vectorizers.git
    - top2vec
    - hnxwidget
    - ripser
    - kmapper
    - persim
    - cdlib
    - leidenalg
    - partition-igraph
  - networkx
  - setuptools
  - wheel
  - git>=2.5
  - sphinx
  - bokeh
  - chardet
  - click
  - colorcet
  - coverage
  - coveralls
  - datashader
  - holoviews
  - humanize
  - matplotlib
  - jupyter
  - jupyterlab
  - scikit-image
  - scikit-learn
  - scipy
  - joblib
  - nb_conda_kernels
  - pandas
  - dask
  - requests
  - pathlib
  - fsspec
  - python=3.7
  - pyarrow
  - psutil
  - cairo
  - pycairo
  - nltk
  - spacy
  - huggingface_hub
  - conda-forge::adlfs
  - conda-forge::umap-learn
  - conda-forge::hdbscan
